const contentPieces = [
  {
    id: 1,
    date: "Miércoles 1 de julio",
    week: "Semana 1",
    format: "Trend",
    network: "Instagram + Facebook",
    pillar: "Contenido de oportunidad",
    sector: "Multisectorial B2B",
    title: "Trend: Fuera de lugar",
    objective: "Aprovechar un contenido de oportunidad ya publicado para mantener presencia activa.",
    hook: "No aplica.",
    cta: "No aplica.",
    content: ["Pieza publicada como contenido de oportunidad."],
    stories: ["No aplica."],
    material: "No aplica.",
    status: "Publicada.",
    alternative: "No aplica.",
    priority: "No aplica.",
    tags: ["Instagram / Facebook", "Trend", "Publicadas", "Contenido de oportunidad"]
  },
  {
    id: 2,
    date: "Viernes 3 de julio",
    week: "Semana 1",
    format: "Post + adaptación",
    network: "LinkedIn",
    adaptation: "Instagram + Facebook",
    pillar: "Seguimiento y trazabilidad",
    sector: "Multisectorial B2B",
    title: "¿Qué debería dejar claro una visita técnica?",
    objective: "Reforzar el valor de la claridad posterior a una visita técnica.",
    hook: "No aplica.",
    cta: "No aplica.",
    content: ["Pieza publicada con adaptación editorial para Instagram y Facebook."],
    stories: ["No aplica."],
    material: "No aplica.",
    status: "Publicada.",
    alternative: "No aplica.",
    priority: "No aplica.",
    tags: ["LinkedIn", "Instagram / Facebook", "Post", "Publicadas", "Seguimiento"]
  },
  {
    id: 3,
    date: "Lunes 6 de julio",
    week: "Semana 2",
    format: "Estático",
    network: "Instagram + Facebook",
    pillar: "Prevención articulada",
    sector: "Multisectorial B2B",
    title: "La prevención funciona cuando todas las áreas se conectan",
    objective: "Mostrar la prevención como trabajo coordinado entre áreas.",
    hook: "No aplica.",
    cta: "No aplica.",
    content: ["La prevención mejora cuando áreas operativas, administrativas y técnicas trabajan conectadas."],
    stories: ["No aplica."],
    material: "No aplica.",
    status: "Publicada.",
    alternative: "No aplica.",
    priority: "No aplica.",
    tags: ["Instagram / Facebook", "Estático", "Publicadas", "Prevención"]
  },
  {
    id: 4,
    date: "Martes 7 de julio",
    week: "Semana 2",
    format: "Estático",
    network: "Instagram + Facebook",
    pillar: "Contenido de oportunidad",
    sector: "Multisectorial B2B",
    title: "Permiso de no ingreso: Colombia vs. Suiza",
    objective: "Aprovechar una conversación de oportunidad desde una mirada editorial de marca.",
    hook: "No aplica.",
    cta: "No aplica.",
    content: ["Contenido de oportunidad publicado para mantener presencia y conversación contextual."],
    stories: ["No aplica."],
    material: "No aplica.",
    status: "Publicada.",
    alternative: "No aplica.",
    priority: "No aplica.",
    tags: ["Instagram / Facebook", "Estático", "Publicadas", "Contenido de oportunidad"]
  },
  {
    id: 5,
    date: "Jueves 9 de julio",
    week: "Semana 2",
    format: "Reel con vocero",
    network: "Instagram, Facebook, TikTok y YouTube Shorts",
    pillar: "Contenido humano / TKC Corp",
    sector: "Multisectorial B2B",
    title: "¿Cuánto cuesta reaccionar tarde? (Reel 04)",
    objective: "Conectar prevención temprana con pérdidas operativas, sanitarias y de confianza.",
    hook: "La identificación temprana evita pérdidas operativas. ¿Tu empresa sabe qué señales detectar?",
    cta: "Es mejor prevenir y actuar ahora.",
    content: [
      "Costo real de reaccionar tarde.",
      "Pérdidas operativas.",
      "Riesgos sanitarios.",
      "Pérdida de confianza."
    ],
    stories: ["No aplica."],
    material: "Ya grabado — usar guion y clips existentes.",
    status: "Pendiente de edición.",
    alternative: "No aplica.",
    priority: "Alta",
    tags: ["Reel", "TikTok", "YouTube Shorts", "Contenido humano", "Alta prioridad"]
  },
  {
    id: 6,
    date: "Viernes 10 de julio",
    week: "Semana 2",
    format: "Expediente técnico",
    network: "Instagram + Facebook + LinkedIn",
    pillar: "Hídriko",
    sector: "Tanques y operaciones institucionales",
    title: "Expediente Hídriko No. 0426",
    objective: "Presentar un hallazgo real anonimizado con enfoque técnico y documental.",
    hook: "Este no es un caso hipotético.",
    cta: "Si tu último informe de tanque tiene más de un año, probablemente deberías abrir uno.",
    content: ["Hallazgo real anonimizado presentado como expediente."],
    stories: ["No aplica."],
    material: "Caso real anonimizado (validar con operación).",
    status: "Requiere validación.",
    alternative: "Expediente basado en patrón típico documentado.",
    priority: "Alta",
    tags: ["Instagram / Facebook", "LinkedIn", "Expediente técnico", "Hídriko", "Requiere validación", "Alta prioridad"]
  },
  {
    id: 7,
    date: "Martes 14 de julio",
    week: "Semana 3",
    format: "Duelo con voz en off",
    network: "Instagram + TikTok",
    pillar: "Centros comerciales",
    sector: "Centros comerciales",
    title: "Administrador vs. técnico",
    objective: "Contrastar percepción administrativa con criterio técnico.",
    hook: "Esta semana volvimos a escuchar la misma frase...",
    cta: "¿Tú qué hubieras dicho?",
    content: ["Contraste de percepción vs. criterio técnico."],
    stories: ["No aplica."],
    material: "Dos personas de TKC grabando cada rol — confirmado.",
    status: "Listo para producir.",
    alternative: "No aplica.",
    priority: "Alta",
    tags: ["Instagram / Facebook", "TikTok", "Video", "Centros comerciales", "Alta prioridad"]
  },
  {
    id: 8,
    date: "Miércoles 15 de julio",
    week: "Semana 3",
    format: "Carta ejecutiva",
    network: "LinkedIn",
    pillar: "Diferenciales / LinkedIn ejecutivo",
    sector: "Multisectorial B2B",
    title: "Una carta abierta a quien compara cotizaciones solo por precio",
    objective: "Elevar la conversación sobre decisión de proveedor más allá del precio.",
    hook: "Esto no es una publicación de marketing. Es algo que quería decir directamente.",
    cta: "Ojalá esto le sirva a alguien que está por decidir.",
    content: ["Por qué el precio no es la variable correcta."],
    stories: ["No aplica."],
    material: "Aprobación de gerencia (tono en primera persona).",
    status: "Requiere validación.",
    alternative: "Nota editorial sin firma personal.",
    priority: "Alta",
    tags: ["LinkedIn", "Carta ejecutiva", "Diferenciales", "Requiere validación", "Alta prioridad"]
  },
  {
    id: 9,
    date: "Jueves 16 de julio",
    week: "Semana 3",
    format: "Reel demostrativo",
    network: "Instagram, Facebook, TikTok y YouTube Shorts",
    pillar: "Criterio técnico / campo",
    sector: "Multisectorial B2B",
    title: "Control pasivo de insectos rastreros",
    objective: "Mostrar que el criterio técnico no siempre implica aplicar producto de inmediato.",
    hook: "La mayoría cree que controlar una plaga es aplicar algo. A veces es no aplicar nada — todavía.",
    cta: "¿Sabías que existía esta opción?",
    content: ["Demostración real de control pasivo y criterio técnico en campo."],
    stories: ["No aplica."],
    material: "Grabación confirmada sábado 11 de julio. Si se graban tomas extra de trampas o accesorios de monitoreo, guardarlas para la pieza 17 del 28 de julio.",
    status: "Pendiente de grabación (confirmada).",
    alternative: "No aplica.",
    priority: "Alta",
    tags: ["Reel", "Instagram / Facebook", "TikTok", "YouTube Shorts", "Criterio técnico", "Alta prioridad"]
  },
  {
    id: 10,
    date: "Viernes 17 de julio",
    week: "Semana 3",
    format: "Bitácora técnica",
    network: "Instagram + Facebook + LinkedIn",
    pillar: "TKC Security (SST)",
    sector: "Empresas e instituciones",
    title: "Bitácora — ruta de evacuación bloqueada",
    objective: "Mostrar TKC Security como revisión, prevención y seguimiento operativo.",
    hook: "Entrada de bitácora, 17 de julio.",
    cta: "Registrado. Seguimiento programado.",
    content: ["Registro real de una visita SST, no solo extintores."],
    stories: ["No aplica."],
    material: "Caso real o recreación fiel (validar con SST).",
    status: "Requiere validación.",
    alternative: "Bitácora basada en hallazgos típicos.",
    priority: "Alta",
    tags: ["Instagram / Facebook", "LinkedIn", "Bitácora técnica", "TKC Security", "Requiere validación", "Alta prioridad"]
  },
  {
    id: 11,
    date: "Martes 21 de julio",
    week: "Semana 4",
    format: "Línea de tiempo / mini doc",
    network: "Instagram, Facebook, TikTok, YouTube Shorts y LinkedIn",
    pillar: "Historia y trayectoria",
    sector: "Multisectorial B2B",
    title: "2004: una empresa que decidió no ser como las demás",
    objective: "Construir confianza desde historia, origen y criterio de marca.",
    hook: "Esto no empezó como una empresa de fumigación.",
    cta: "Han pasado 20 años. La decisión sigue siendo la misma.",
    content: ["Fundación como decisión de posicionamiento."],
    stories: ["No aplica."],
    material: "Foto de archivo si existe.",
    status: "Requiere material.",
    alternative: "Versión tipográfica/motion sin fotos.",
    priority: "Alta",
    tags: ["Reel", "LinkedIn", "TikTok", "YouTube Shorts", "Historia", "Requiere material", "Alta prioridad"]
  },
  {
    id: 12,
    date: "Miércoles 22 de julio",
    week: "Semana 4",
    format: "Pregunta directa a cámara",
    network: "TikTok + Instagram Reels",
    pillar: "Hoteles",
    sector: "Hoteles",
    title: "Pregunta incómoda — chinches en hoteles",
    objective: "Abrir conversación técnica y directa sobre un riesgo sensible en hotelería.",
    hook: "Pregunta incómoda para quien administra un hotel...",
    cta: "Silencio, sin CTA de venta.",
    content: ["Pregunta directa a cámara con tono seco y técnico."],
    stories: ["No aplica."],
    material: "Vocero dispuesto al tono seco.",
    status: "Requiere material.",
    alternative: "Versión narrada con texto si no hay vocero disponible.",
    priority: "Alta",
    tags: ["Reel", "TikTok", "Hoteles", "Requiere material", "Alta prioridad"]
  },
  {
    id: 13,
    date: "Jueves 23 de julio",
    week: "Semana 4",
    format: "Caso anonimizado narrado",
    network: "Instagram + Facebook",
    pillar: "Colegios y clínicas",
    sector: "Colegios y clínicas",
    title: "La llamada llegó un lunes",
    objective: "Narrar un caso real anonimizado como historia corta.",
    hook: "Arranca con la llamada.",
    cta: "Sin CTA explícito.",
    content: ["Caso real anonimizado como historia corta."],
    stories: ["No aplica."],
    material: "Ninguno — patrón documentado.",
    status: "Listo para producir.",
    alternative: "No aplica.",
    priority: "Alta",
    tags: ["Instagram / Facebook", "Caso narrado", "Colegios y clínicas", "Alta prioridad"]
  },
  {
    id: 14,
    date: "Viernes 24 de julio",
    week: "Semana 4",
    format: "Carrusel de citas gráficas",
    network: "Instagram + Facebook + LinkedIn",
    pillar: "Testimonios / prueba social",
    sector: "Multisectorial B2B",
    title: "Lo que dicen quienes ya trabajan con TKC",
    objective: "Usar testimonios reales como prueba social sobria y B2B.",
    hook: "Cada slide es una cita real, sin intro.",
    cta: "Sin CTA de venta — cierre con la cita.",
    content: ["Compilar 3-4 testimonios breves de clientes reales."],
    stories: ["No aplica."],
    material: "Mínimo 3 testimonios reales (texto o mensaje, no requiere grabación).",
    status: "Requiere validación.",
    alternative: "Publicar con los que estén listos, aunque sean 2.",
    priority: "Alta",
    tags: ["Instagram / Facebook", "LinkedIn", "Carrusel", "Testimonios", "Requiere validación", "Alta prioridad"]
  },
  {
    id: 15,
    date: "Lunes 27 de julio",
    week: "Semana 5",
    format: "Entrevista rápida",
    network: "Instagram + TikTok + YouTube Shorts",
    pillar: "Propiedad horizontal",
    sector: "Propiedad horizontal",
    title: "5 preguntas rápidas a un técnico sobre conjuntos residenciales",
    objective: "Resolver preguntas de propiedad horizontal en formato dinámico.",
    hook: "Primera pregunta directa a cámara.",
    cta: "Invita a dejar una pregunta en comentarios.",
    content: ["Formato dinámico con respuestas cortas."],
    stories: ["No aplica."],
    material: "Técnico disponible.",
    status: "Requiere material.",
    alternative: "Preguntas y respuestas en texto.",
    priority: "Media",
    tags: ["Reel", "TikTok", "YouTube Shorts", "Propiedad horizontal", "Requiere material"]
  },
  {
    id: 16,
    date: "Lunes 27 de julio",
    week: "Semana 5",
    format: "Glosario técnico 30s",
    network: "LinkedIn",
    pillar: "Alimentos",
    sector: "Restaurantes y alimentos",
    title: "¿Qué es un vector?",
    objective: "Explicar un término técnico de forma simple, útil y consultable.",
    hook: "Hay una palabra que casi nadie explica: vector.",
    cta: "Ahora ya sabes qué preguntar.",
    content: ["Glosario técnico breve para explicar qué es un vector en contexto de alimentos y saneamiento."],
    stories: ["No aplica."],
    material: "Solo diseño/motion.",
    status: "Listo para producir.",
    alternative: "No aplica.",
    priority: "Media",
    tags: ["LinkedIn", "Glosario técnico", "Alimentos"]
  },
  {
    id: 17,
    date: "Martes 28 de julio",
    week: "Semana 5",
    format: "Carrusel catálogo",
    network: "Instagram + Facebook",
    pillar: "Diferenciales / criterio técnico",
    sector: "Multisectorial B2B",
    title: "Tipos de equipos que usamos",
    objective: "Mostrar que fumigar es solo una palabra general y que detrás hay herramientas distintas según el caso.",
    hook: "'Fumigar' es una palabra. Estas son las herramientas reales detrás.",
    cta: "Cada situación tiene su herramienta correcta.",
    content: ["Catálogo visual de equipos, herramientas y criterio técnico de selección."],
    stories: ["No aplica."],
    material: "Fotos reales de equipos (confirmar). Reutilizar tomas extra de trampas o accesorios de monitoreo grabadas el sábado 11 de julio si quedan disponibles.",
    status: "Requiere material.",
    alternative: "Carrusel con diseño e íconos si no hay fotos suficientes.",
    priority: "Media",
    tags: ["Instagram / Facebook", "Carrusel", "Diferenciales", "Requiere material"]
  },
  {
    id: 18,
    date: "Miércoles 29 de julio",
    week: "Semana 5",
    format: "Expediente técnico",
    network: "Instagram + Facebook + LinkedIn",
    pillar: "Bodegas / industria",
    sector: "Bodegas / industria",
    title: "Expediente TKC No. 0512",
    objective: "Consolidar una serie reconocible de expedientes técnicos anonimizada.",
    hook: "Este expediente estuvo cerca de no abrirse.",
    cta: "Cierre reflexivo.",
    content: ["Caso anonimizado, serie reconocible."],
    stories: ["No aplica."],
    material: "Caso real anonimizado (validar).",
    status: "Requiere validación.",
    alternative: "Expediente basado en patrón típico.",
    priority: "Media",
    tags: ["Instagram / Facebook", "LinkedIn", "Expediente técnico", "Bodegas", "Requiere validación"]
  },
  {
    id: 19,
    date: "Jueves 30 de julio",
    week: "Semana 5",
    format: "Reveal de datos",
    network: "LinkedIn",
    pillar: "Certificaciones",
    sector: "Multisectorial B2B",
    title: "3 sellos. 3 auditorías externas",
    objective: "Explicar certificaciones y respaldo técnico como prueba de procesos auditados.",
    hook: "3 sellos. 3 auditorías externas. Esto es lo que representan.",
    cta: "Puedes pedir ver el certificado cuando quieras.",
    content: ["ISO 9001/14001/45001 + PREAD explicadas como respaldo externo y verificable."],
    stories: ["No aplica."],
    material: "Confirmar vigencia de certificaciones.",
    status: "Requiere validación.",
    alternative: "Publicar sin mencionar vigencia exacta.",
    priority: "Alta",
    tags: ["LinkedIn", "Carta ejecutiva", "Certificaciones", "Requiere validación", "Alta prioridad"]
  },
  {
    id: 20,
    date: "Viernes 31 de julio",
    week: "Semana 5",
    format: "Reel con cliente real",
    network: "Instagram + Facebook + TikTok + LinkedIn",
    pillar: "Testimonios / prueba social",
    sector: "Multisectorial B2B",
    title: "El cliente habla, no TKC",
    objective: "Cerrar julio con prueba social real desde la voz del cliente.",
    hook: "Primeras palabras reales del cliente, en video.",
    cta: "Sin CTA durante el video — cierre solo con logo.",
    content: ["Cliente(s) real(es) en su propia locación, no imágenes genéricas."],
    stories: ["No aplica."],
    material: "Cliente(s) dispuesto(s) a grabar en cámara, en su locación real.",
    status: "Requiere validación.",
    alternative: "Voz real + imágenes reales de su operación si no quiere cámara.",
    priority: "Alta",
    tags: ["Reel", "Instagram / Facebook", "LinkedIn", "TikTok", "Testimonios", "Requiere validación", "Alta prioridad"]
  }
];

const specialStories = [
  {
    date: "Lunes 13 de julio",
    title: "Festivo — Rosario de Chiquinquirá — sin publicación",
    text: "No se programa publicación de feed.",
    note: "Sin publicación."
  },
  {
    date: "Lunes 20 de julio",
    title: "Historia institucional únicamente",
    text: "Hoy es un día para desconectar.",
    note: "Festivo Independencia · Sin CTA comercial · Fuera del conteo de 20."
  }
];
